# Erivando Sena<erivando.sena@aluno.uece.br>

services:

  neo4j_core_1:
    build:
      context: .
      dockerfile: Dockerfile.neo4j  # Usando o Dockerfile de Mining Challenge do dump
    container_name: neo4j_core_1
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_memory_heap_initial__size=512M
      - NEO4J_dbms_memory_heap_max__size=4G
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms_mode=CORE
      - NEO4J_dbms.default_listen_address=0.0.0.0
      - NEO4J_AUTH=neo4j/Password1
    volumes:
      - ./volumes/neo4j-data-core1:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7474 || exit 1"]
      interval: 5s
      retries: 5

  neo4j_core_2:
    image: neo4j:4.4.36-community
    container_name: neo4j_core_2
    ports:
      - "7475:7474"
      - "7688:7687"
    environment:
      - NEO4J_dbms_memory_heap_initial__size=512M
      - NEO4J_dbms_memory_heap_max__size=3G
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms_mode=CORE
      - NEO4J_dbms.default_listen_address=0.0.0.0
      - NEO4J_AUTH=neo4j/Password1
    volumes:
      - ./volumes/neo4j-data-core2:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7474 || exit 1"]
      interval: 5s
      retries: 5

  neo4j_replica_1:
    image: neo4j:4.4.36-community
    container_name: neo4j_replica_1
    ports:
      - "7476:7474"
      - "7689:7687"
    environment:
      - NEO4J_dbms_memory_heap_initial__size=512M
      - NEO4J_dbms_memory_heap_max__size=3G
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms_mode=READ_REPLICA
      - NEO4J_dbms.default_listen_address=0.0.0.0
      - NEO4J_AUTH=neo4j/Password1
    volumes:
      - ./volumes/neo4j-data-replica1:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7474 || exit 1"]
      interval: 5s
      retries: 5

  neo4j_replica_2:
    image: neo4j:4.4.36-community
    container_name: neo4j_replica_2
    ports:
      - "7477:7474"
      - "7690:7687"
    environment:
      - NEO4J_dbms_memory_heap_initial__size=512M
      - NEO4J_dbms_memory_heap_max__size=3G
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms_mode=READ_REPLICA
      - NEO4J_dbms.default_listen_address=0.0.0.0
      - NEO4J_AUTH=neo4j/Password1
    volumes:
      - ./volumes/neo4j-data-replica2:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7474 || exit 1"]
      interval: 5s
      retries: 5

  weaver:
    build:
      context: .
      dockerfile: Dockerfile.weaver
    container_name: goblinWeaver
    ports:
      - "8080:8080"
    depends_on:
      neo4j_core_1:
        condition: service_healthy
    environment:
      - NEO4J_URI=bolt://neo4jMaven:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=Password1
