services:

  neo4j:
    build:
      context: .
      dockerfile: Dockerfile.neo4j
    container_name: neo4jMaven
    ports:
      - "7474:7474"
      - "7687:7687"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7474 || exit 1"]
      interval: 5s
      retries: 5
    environment:
      # memória Heap
      - NEO4J_dbms_memory_heap_initial__size=512M
      - NEO4J_dbms_memory_heap_max__size=6G
      # Page Cache
      - NEO4J_dbms_memory_pagecache_size=512M
      # memória de transações
      - NEO4J_dbms_memory_transaction_total__max=512M
    volumes:
      - neo4j-data:/data

  weaver:
    build:
      context: .
      dockerfile: Dockerfile.weaver
    container_name: goblinWeaver
    ports:
      - "8080:8080"
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - NEO4J_URI=bolt://neo4jMaven:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=Password1

volumes:
  neo4j-data: